# Standards: 1.2
---
- name: "Delete DNS record : {{ certificate.name }}"
  loop: "{{ letsencrypt_initial_request.challenge_data_dns | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - letsencrypt_initial_request is changed
    - letsencrypt_cluster_nodes | length == 0 or inventory_hostname == letsencrypt_cluster_nodes[0]
    - letsencrypt_initial_request.challenge_data_dns | length > 0
  nsupdate:
    key_algorithm: "{{ certificate.nsupdate.algorithm | default(letsencrypt_nsupdate_algorithm) }}"
    key_name: "{{ certificate.nsupdate.name | default(letsencrypt_nsupdate_name) }}"
    key_secret: "{{ certificate.nsupdates.ecret | default(letsencrypt_nsupdate_secret) }}"
    server: "{{ certificate.nsupdate_server | default(letsencrypt_nsupdate_server) }}"
    zone: "{{ certificate.zone }}"
    type: TXT
    record: "{{ item.key }}."
    state: absent
  tags:
    - letsencrypt

...
