---
- name: "Write SSL config : {{ certificate.name }}"
  register: letsencrypt_ssl_config
  ansible.builtin.template:
    src: openssl.cnf.j2
    dest: "/etc/letsencrypt/confs/{{ certificate.name }}.cnf"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - letsencrypt

- name: "Remove old cert : {{ certificate.name }}"
  when: letsencrypt_ssl_config is changed
  loop:
    - "/etc/letsencrypt/csrs/{{ certificate.name }}.csr"
    - "/etc/letsencrypt/keys/{{ certificate.name }}.key"
    - "/etc/letsencrypt/certs/{{ certificate.name }}.crt"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  tags:
    - letsencrypt
    - skip_ansible_later

- name: "Create new cert : {{ certificate.name }}"
  when: letsencrypt_ssl_config is changed
  ansible.builtin.command: "openssl req -out csrs/{{ certificate.name }}.csr -newkey rsa:2048 -nodes -keyout keys/{{ certificate.name }}.key -config confs/{{ certificate.name }}.cnf -batch"
  args:
    chdir: /etc/letsencrypt
    creates: "/etc/letsencrypt/keys/{{ certificate.name }}.key"
  tags:
    - letsencrypt
    - skip_ansible_later

...
